.zshrc edited and zshrc aliases markdown added

diff --git a/configs/zshrc_SAFE b/configs/zshrc_SAFE
--- a/configs/zshrc_SAFE
+++ b/configs/zshrc_SAFE
@@ -115,17 +115,19 @@ bindkey "^S" history-incremental-pattern-search-forward
 # Aliases
 alias reboot='sudo reboot +0'
 alias shutdown='sudo shutdown +0'
-#alias ls='ls --color=auto --human-readable --group-directories-first --classify'
-#alias ll='ls --color=auto --human-readable --group-directories-first --classify -l'
-#alias lla='ls --color=auto --human-readable --group-directories-first --classify -la'
+alias h="history | grep "
+alias ezrc='nano ~/.zshrc'
+alias hlp='cat ~/zshrc_aliases.md'
+alias vi='nvim'
+alias svi='sudo vi'
+alias vis='nvim "+set si"'
 alias vim='nvim'
 alias c='clear'
 alias cp='cp -iv --reflink=auto'
 alias rcp='rsync -v --progress'
 alias rmv='rsync -v --progress --remove-source-files'
 alias mv='mv -iv'
-alias rm='rm -iv'
-alias rmdir='rmdir -v'
+alias less='less -R'
 alias ln='ln -v'
 alias chmod='chmod -c'
 alias chown='chown -c'
@@ -146,6 +148,28 @@ alias rmd='rm -rf'
 alias ping='ping -c 10'
 alias x='exit'
 alias ff='fastfetch'
+alias multitail='multitail --no-repeat -c'
+alias freshclam='sudo freshclam'
+alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
+alias da='date "+%Y-%m-%d %A %T %Z"'
+
+# Change directory aliases
+alias home='cd ~'
+alias cd..='cd ..'
+alias ..='cd ..'
+alias ...='cd ../..'
+alias ....='cd ../../..'
+alias .....='cd ../../../..'
+
+# alias chmod commands
+alias mx='chmod a+x'
+alias 000='chmod -R 000'
+alias 644='chmod -R 644'
+alias 666='chmod -R 666'
+alias 755='chmod -R 755'
+alias 777='chmod -R 777'
+
+
 
 if command -v bat > /dev/null; then
      alias cat="bat"
@@ -158,6 +182,53 @@ if command -v colordiff > /dev/null 2>&1; then
 else
     alias diff="diff -Nuar"
 fi
+
+# Alias's for archives
+alias mktar='tar -cvf'
+alias mkbz2='tar -cvjf'
+alias mkgz='tar -cvzf'
+alias untar='tar -xvf'
+alias unbz2='tar -xvjf'
+alias ungz='tar -xvzf'
+
+# Extracts any archive(s) (if unp isn't installed)
+extract() {
+    for archive in "$@"; do
+        if [ -f "$archive" ]; then
+            case $archive in
+            *.tar.bz2) tar xvjf $archive ;;
+            *.tar.gz) tar xvzf $archive ;;
+            *.bz2) bunzip2 $archive ;;
+            *.rar) rar x $archive ;;
+            *.gz) gunzip $archive ;;
+            *.tar) tar xvf $archive ;;
+            *.tbz2) tar xvjf $archive ;;
+            *.tgz) tar xvzf $archive ;;
+            *.zip) unzip $archive ;;
+            *.Z) uncompress $archive ;;
+            *.7z) 7z x $archive ;;
+            *) echo "don't know how to extract '$archive'..." ;;
+            esac
+        else
+            echo "'$archive' is not a valid file!"
+        fi
+    done
+}
+
+# Searches for text in all files in the current folder
+ftext() {
+    # -i case-insensitive
+    # -I ignore binary files
+    # -H causes filename to be printed
+    # -r recursive search
+    # -n causes line number to be printed
+    # optional: -F treat search term as a literal, not a regular expression
+    # optional: -l only print filenames and not the matching lines ex. grep -irl "$1" *
+    grep -iIHrn --color=always "$1" . | less -r
+}
+
+# Alias to show football fixtures
+alias ffix='~/dwm/scripts/footballfix'
 
 # Alias to show all established connections and their resolved names
 alias show_connections='sudo netstat -tupn | grep "ESTABLISHED" | awk '\''{print $5}'\'' | cut -d: -f1 | sort | uniq | xargs -I {} sh -c '\''echo -n "{}: "; nslookup {}'\'' | grep "name ="'
@@ -189,3 +260,281 @@ weather() {
 alias wttr=weather
 
 alias opwttr='~/dwm/scripts/OpWeatherinfo'
+
+# IP address lookup
+alias whatismyip="whatsmyip"
+function whatsmyip ()
+{
+    # Internal IP Lookup.
+    if [ -e /usr/bin/ip ]; then
+        echo -n "Internal IP: "
+        /usr/bin/ip addr show wlp0s20f3 | grep "inet " | awk -F: '{print $1}' | awk '{print $2}'
+    else
+        echo -n "Internal IP: "
+        /usr/bin/ifconfig wlp0s20f3 | grep "inet " | awk -F: '{print $1} |' | awk '{print $2}'
+    fi
+
+    # External IP Lookup
+    echo -n "External IP: "
+    curl -s ifconfig.me
+}
+
+# Search running processes
+alias p="ps aux | grep "
+alias topcpu="/bin/ps -eo pcpu,pid,user,args | sort -k 1 -r | head -10"
+
+# Search files in the current folder
+alias f="find . | grep "
+
+# Count all files (recursively) in the current folder
+alias countfiles="for t in files links directories; do echo \`find . -type \${t:0:1} | wc -l\` \$t; done 2> /dev/null"
+
+# To see if a command is aliased, a file, or a built-in command
+alias checkcommand="type -t"
+
+# Show open ports
+alias openports='netstat -nape --inet'
+
+# Alias's to show disk space and space used in a folder
+alias diskspace="du -S | sort -n -r |more"
+alias folders='du -h --max-depth=1'
+alias folderssort='find . -maxdepth 1 -type d -print0 | xargs -0 du -sk | sort -rn'
+alias treed='tree -CAFd'
+alias mountedinfo='df -hT'
+
+# Show all logs in /var/log
+alias logs="sudo find /var/log -type f -exec file {} \; | grep 'text' | cut -d' ' -f1 | sed -e's/:$//g' | grep -v '[0-9]$' | xargs sudo tail -f"
+
+# SHA1
+alias sha1='openssl sha1'
+
+alias clickpaste='sleep 3; xdotool type "$(xclip -o -selection clipboard)"'
+
+# KITTY - alias to be able to use kitty features when connecting to remote servers(e.g use tmux on remote server)
+
+alias kssh="kitty +kitten ssh"
+
+
+# Copy file with a progress bar
+cpp() {
+    set -e
+    strace -q -ewrite cp -- "${1}" "${2}" 2>&1 |
+        awk '{
+    count += $NF
+    if (count % 10 == 0) {
+        percent = count / total_size * 100
+        printf "%3d%% [", percent
+        for (i=0;i<=percent;i++)
+            printf "="
+            printf ">"
+            for (i=percent;i<100;i++)
+                printf " "
+                printf "]\r"
+            }
+        }
+    END { print "" }' total_size="$(stat -c '%s' "${1}")" count=0
+}
+
+# Copy and go to the directory
+cpg() {
+    if [ -d "$2" ]; then
+        cp "$1" "$2" && cd "$2"
+    else
+        cp "$1" "$2"
+    fi
+}
+
+# Move and go to the directory
+mvg() {
+    if [ -d "$2" ]; then
+        mv "$1" "$2" && cd "$2"
+    else
+        mv "$1" "$2"
+    fi
+}
+
+# Create and go to the directory
+mkdirg() {
+    mkdir -p "$1"
+    cd "$1"
+}
+
+# Goes up a specified number of directories  (i.e. up 4)
+up() {
+    local d=""
+    limit=$1
+    for ((i = 1; i <= limit; i++)); do
+        d=$d/..
+    done
+    d=$(echo $d | sed 's/^\///')
+    if [ -z "$d" ]; then
+        d=..
+    fi
+    cd $d
+}
+
+# Returns the last 2 fields of the working directory
+pwdtail() {
+    pwd | awk -F/ '{nlast = NF -1;print $nlast"/"$NF}'
+}
+
+# Show the current distribution
+distribution ()
+{
+    local dtype="unknown"  # Default to unknown
+
+    # Use /etc/os-release for modern distro identification
+    if [ -r /etc/os-release ]; then
+        source /etc/os-release
+        case $ID in
+            fedora|rhel|centos)
+                dtype="redhat"
+                ;;
+            sles|opensuse*)
+                dtype="suse"
+                ;;
+            ubuntu|debian)
+                dtype="debian"
+                ;;
+            gentoo)
+                dtype="gentoo"
+                ;;
+            arch)
+                dtype="arch"
+                ;;
+            slackware)
+                dtype="slackware"
+                ;;
+            *)
+                # If ID is not recognized, keep dtype as unknown
+                ;;
+        esac
+    fi
+
+    echo $dtype
+}
+
+# Show the current version of the operating system
+ver() {
+    local dtype
+    dtype=$(distribution)
+
+    case $dtype in
+        "redhat")
+            if [ -s /etc/redhat-release ]; then
+                cat /etc/redhat-release
+            else
+                cat /etc/issue
+            fi
+            uname -a
+            ;;
+        "suse")
+            cat /etc/SuSE-release
+            ;;
+        "debian")
+            lsb_release -a
+            ;;
+        "gentoo")
+            cat /etc/gentoo-release
+            ;;
+        "arch")
+            cat /etc/os-release
+            ;;
+        "slackware")
+            cat /etc/slackware-version
+            ;;
+        *)
+            if [ -s /etc/issue ]; then
+                cat /etc/issue
+            else
+                echo "Error: Unknown distribution"
+                exit 1
+            fi
+            ;;
+    esac
+}
+
+# View Apache logs
+apachelog() {
+    if [ -f /etc/httpd/conf/httpd.conf ]; then
+        cd /var/log/httpd && ls -xAh && multitail --no-repeat -c -s 2 /var/log/httpd/*_log
+    else
+        cd /var/log/apache2 && ls -xAh && multitail --no-repeat -c -s 2 /var/log/apache2/*.log
+    fi
+}
+
+# Edit the Apache configuration
+apacheconfig() {
+    if [ -f /etc/httpd/conf/httpd.conf ]; then
+        nano /etc/httpd/conf/httpd.conf
+    elif [ -f /etc/apache2/apache2.conf ]; then
+        nano /etc/apache2/apache2.conf
+    else
+        echo "Error: Apache config file could not be found."
+        echo "Searching for possible locations:"
+        sudo updatedb && locate httpd.conf && locate apache2.conf
+    fi
+}
+
+# Edit the PHP configuration file
+phpconfig() {
+    if [ -f /etc/php.ini ]; then
+        nano /etc/php.ini
+    elif [ -f /etc/php/php.ini ]; then
+        nano /etc/php/php.ini
+    elif [ -f /etc/php5/php.ini ]; then
+        nano /etc/php5/php.ini
+    elif [ -f /usr/bin/php5/bin/php.ini ]; then
+        nano /usr/bin/php5/bin/php.ini
+    elif [ -f /etc/php5/apache2/php.ini ]; then
+        nano /etc/php5/apache2/php.ini
+    else
+        echo "Error: php.ini file could not be found."
+        echo "Searching for possible locations:"
+        sudo updatedb && locate php.ini
+    fi
+}
+
+# Edit the MySQL configuration file
+mysqlconfig() {
+    if [ -f /etc/my.cnf ]; then
+        nano /etc/my.cnf
+    elif [ -f /etc/mysql/my.cnf ]; then
+        nano /etc/mysql/my.cnf
+    elif [ -f /usr/local/etc/my.cnf ]; then
+        nano /usr/local/etc/my.cnf
+    elif [ -f /usr/bin/mysql/my.cnf ]; then
+        nano /usr/bin/mysql/my.cnf
+    elif [ -f ~/my.cnf ]; then
+        nano ~/my.cnf
+    elif [ -f ~/.my.cnf ]; then
+        nano ~/.my.cnf
+    else
+        echo "Error: my.cnf file could not be found."
+        echo "Searching for possible locations:"
+        sudo updatedb && locate my.cnf
+    fi
+}
+
+
+# Trim leading and trailing spaces (for scripts)
+trim() {
+    local var=$*
+    var="${var#"${var%%[![:space:]]*}"}" # remove leading whitespace characters
+    var="${var%"${var##*[![:space:]]}"}" # remove trailing whitespace characters
+    echo -n "$var"
+}
+
+# GitHub FAM007E Additions
+
+gcom() {
+    git add .
+    git commit -m "$1"
+}
+
+lazyg() {
+    git add .
+    git commit -m "$1"
+    git push
+}
+
